#!/usr/bin/env python3
"""
update_pages.py — Regenerate GitHub Pages content from repository state
=======================================================================

This script scans the repository and updates:
    1. docs/index.md — navigation hub with accurate links
    2. sitemap.xml — updated lastmod timestamps
    3. Generates data/labs-certs.md and data/labs-certs.json from the
       SQLite database (if it exists)

The script is designed to be run manually or via GitHub Actions to keep
the portfolio site in sync with the actual repository contents.

Usage:
    python scripts/update_pages.py

Dependencies:
    - Python 3.10+ (uses pathlib, sqlite3 from stdlib)
    - No external packages required
"""

import json
import os
import sqlite3
import sys
from datetime import date, datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Root of the repository (parent of the scripts/ directory)
REPO_ROOT = Path(__file__).resolve().parent.parent

# Paths to generated/updated files
DOCS_INDEX = REPO_ROOT / "docs" / "index.md"
SITEMAP = REPO_ROOT / "sitemap.xml"
DB_PATH = REPO_ROOT / "data" / "labs-certs.db"
EXPORT_MD = REPO_ROOT / "data" / "labs-certs.md"
EXPORT_JSON = REPO_ROOT / "data" / "labs-certs.json"

# Directories to skip when scanning
SKIP_DIRS = {".git", ".vs", "__pycache__", "node_modules", ".venv", "venv"}

# Base URL for GitHub Pages
PAGES_BASE = "https://tometri.github.io/ProjectPortfolio/"
REPO_URL = "https://github.com/Tometri/ProjectPortfolio"


# ---------------------------------------------------------------------------
# Helper: scan repository structure
# ---------------------------------------------------------------------------

def scan_repo() -> dict:
    """
    Scan the repository and return a structured dictionary of contents.

    Returns a dict with keys:
        - school_courses: list of course folder names
        - labs: list of lab project folders
        - self_study: list of self-study items
        - top_dirs: list of top-level directories
    """
    result = {
        "school_courses": [],
        "labs": [],
        "self_study": [],
        "top_dirs": [],
    }

    # Find top-level directories
    for item in sorted(REPO_ROOT.iterdir()):
        if item.is_dir() and item.name not in SKIP_DIRS and not item.name.startswith("."):
            result["top_dirs"].append(item.name)

    # Scan school courses
    school_base = REPO_ROOT / "school" / "MGCCC-Spring2026"
    if school_base.is_dir():
        for course in sorted(school_base.iterdir()):
            if course.is_dir():
                result["school_courses"].append(course.name)

    # Scan labs — both labs/ and Labs/ directories
    for labs_dir_name in ["labs", "Labs"]:
        labs_dir = REPO_ROOT / labs_dir_name
        if labs_dir.is_dir():
            for item in sorted(labs_dir.rglob("*")):
                if item.is_file() and item.suffix in {".py", ".yaml", ".yml"}:
                    rel = item.relative_to(REPO_ROOT)
                    result["labs"].append(str(rel))

    # Scan self-study
    self_study_dir = REPO_ROOT / "SelfStudy"
    if self_study_dir.is_dir():
        for item in sorted(self_study_dir.rglob("*")):
            if item.is_file() and not item.name.startswith("."):
                rel = item.relative_to(REPO_ROOT)
                if item.suffix.lower() not in {".md"}:
                    result["self_study"].append(str(rel))

    return result


# ---------------------------------------------------------------------------
# Generate docs/index.md
# ---------------------------------------------------------------------------

def generate_docs_index(repo_data: dict) -> None:
    """
    Regenerate docs/index.md based on the actual repository structure.
    This file serves as the central navigation hub for the portfolio.
    """
    lines = [
        "# Repository Index",
        "",
        "<!-- AUTO-GENERATED by scripts/update_pages.py -->",
        f"<!-- Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -->",
        "<!-- Run: python scripts/update_pages.py to regenerate -->",
        "",
        "This file is the navigation hub for the portfolio.",
        "",
        "## Top-Level Areas",
        "",
    ]

    # Top-level directory links
    dir_descriptions = {
        "school": "Academic coursework",
        "SelfStudy": "Self-directed learning",
        "labs": "Hands-on lab exercises",
        "Labs": "Google ADK agent workspace",
        "resume": "Resume documents",
        "StarshipConfig": "Terminal prompt config",
        "scripts": "Maintenance and utility scripts",
        "data": "Labs & certifications database",
        "docs": "Documentation and standards",
        "config": "Configuration templates",
    }

    for dirname in repo_data["top_dirs"]:
        desc = dir_descriptions.get(dirname, "")
        # Check for README files to link to
        readme_candidates = ["README.md", "README.txt", "README.odt"]
        readme_link = None
        for readme in readme_candidates:
            if (REPO_ROOT / dirname / readme).exists():
                readme_link = f"../{dirname}/{readme}"
                break

        if readme_link:
            suffix = f" — {desc}" if desc else ""
            lines.append(f"- [`{dirname}/`]({readme_link}){suffix}")
        else:
            suffix = f" — {desc}" if desc else ""
            lines.append(f"- [`{dirname}/`](../{dirname}/){suffix}")

    # School courses section
    if repo_data["school_courses"]:
        lines.extend([
            "",
            "## School (MGCCC Spring 2026)",
            "",
        ])
        for course in repo_data["school_courses"]:
            lines.append(
                f"- [`{course}`](../school/MGCCC-Spring2026/{course}/)"
            )

    # Labs section
    if repo_data["labs"]:
        lines.extend([
            "",
            "## Labs",
            "",
        ])
        for lab_path in repo_data["labs"]:
            name = Path(lab_path).stem
            lines.append(f"- [`{name}`](../{lab_path})")

    # Self-study section
    if repo_data["self_study"]:
        lines.extend([
            "",
            "## Self-Study",
            "",
        ])
        for item_path in repo_data["self_study"]:
            name = Path(item_path).name
            lines.append(f"- [`{name}`](../{item_path})")

    # Standards section
    lines.extend([
        "",
        "## Standards & Docs",
        "",
        "- [Naming Conventions](naming-conventions.md)",
        "- [Structure Roadmap](portfolio-roadmap.md)",
        "- [Style Guide](../STYLE_GUIDE.md)",
        "- [Contributing](../CONTRIBUTING.md)",
        "- [Maintenance](../MAINTENANCE.md)",
        "",
    ])

    # Write the file
    DOCS_INDEX.parent.mkdir(parents=True, exist_ok=True)
    DOCS_INDEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"  ✓ Updated {DOCS_INDEX.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Update sitemap.xml
# ---------------------------------------------------------------------------

def update_sitemap() -> None:
    """Update sitemap.xml with current date as lastmod."""
    today = date.today().isoformat()
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{PAGES_BASE}</loc>
    <lastmod>{today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>{REPO_URL}</loc>
    <lastmod>{today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>
"""
    SITEMAP.write_text(content, encoding="utf-8")
    print(f"  ✓ Updated {SITEMAP.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Export from database (if it exists)
# ---------------------------------------------------------------------------

def export_from_database() -> None:
    """
    If the labs-certs.db database exists, export its contents to
    Markdown and JSON files for use by the GitHub Pages site.
    """
    if not DB_PATH.exists():
        print("  ⓘ No database found at data/labs-certs.db — skipping export")
        print("    Run: python scripts/database.py init  to create it")
        return

    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row

    # --------------- Export Labs ---------------
    labs = conn.execute(
        "SELECT * FROM labs ORDER BY start_date DESC"
    ).fetchall()

    # --------------- Export Certifications ---------------
    certs = conn.execute(
        "SELECT * FROM certifications ORDER BY issue_date DESC"
    ).fetchall()

    conn.close()

    # --- Generate Markdown ---
    md_lines = [
        "# Labs & Certifications",
        "",
        f"*Auto-generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
    ]

    if certs:
        md_lines.extend(["## Certifications", ""])
        md_lines.append(
            "| Name | Issuer | Issue Date | Status | Credential ID |"
        )
        md_lines.append(
            "|------|--------|-----------|--------|---------------|"
        )
        for cert in certs:
            name = cert["name"]
            issuer = cert["issuer"] or ""
            issue_date = cert["issue_date"] or "—"
            expiry = cert["expiry_date"] or ""
            cred_id = cert["credential_id"] or ""
            status = "Active" if not expiry or expiry >= date.today().isoformat() else "Expired"
            if not cert["issue_date"]:
                status = "In Progress"
            link = cert["verification_link"]
            if link:
                name = f"[{name}]({link})"
            md_lines.append(
                f"| {name} | {issuer} | {issue_date} | {status} | {cred_id} |"
            )
        md_lines.append("")

    if labs:
        md_lines.extend(["## Labs", ""])
        md_lines.append(
            "| Name | Status | Difficulty | Started | Completed |"
        )
        md_lines.append(
            "|------|--------|-----------|---------|-----------|"
        )
        for lab in labs:
            name = lab["name"]
            repo_path = lab["repo_path"]
            if repo_path:
                name = f"[{name}]({repo_path})"
            status = lab["status"] or "—"
            difficulty = lab["difficulty"] or "—"
            start = lab["start_date"] or "—"
            end = lab["completion_date"] or "—"
            md_lines.append(
                f"| {name} | {status} | {difficulty} | {start} | {end} |"
            )
        md_lines.append("")

    EXPORT_MD.parent.mkdir(parents=True, exist_ok=True)
    EXPORT_MD.write_text("\n".join(md_lines), encoding="utf-8")
    print(f"  ✓ Exported {EXPORT_MD.relative_to(REPO_ROOT)}")

    # --- Generate JSON ---
    data = {
        "generated_at": datetime.now().isoformat(),
        "labs": [dict(row) for row in labs],
        "certifications": [dict(row) for row in certs],
    }
    EXPORT_JSON.write_text(
        json.dumps(data, indent=2, default=str),
        encoding="utf-8"
    )
    print(f"  ✓ Exported {EXPORT_JSON.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Run all page update tasks."""
    print("=" * 60)
    print("  ProjectPortfolio — Update Pages")
    print("=" * 60)
    print()

    # Step 1: Scan repository
    print("Scanning repository structure...")
    repo_data = scan_repo()
    print(f"  Found {len(repo_data['top_dirs'])} top-level dirs, "
          f"{len(repo_data['school_courses'])} courses, "
          f"{len(repo_data['labs'])} lab files, "
          f"{len(repo_data['self_study'])} self-study items")
    print()

    # Step 2: Regenerate docs/index.md
    print("Generating docs/index.md...")
    generate_docs_index(repo_data)
    print()

    # Step 3: Update sitemap
    print("Updating sitemap.xml...")
    update_sitemap()
    print()

    # Step 4: Export from database
    print("Exporting from database...")
    export_from_database()
    print()

    print("=" * 60)
    print("  Pages update complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
